HOST = "localhost"
PORT = 8888
PING_MIN_INTERVAL = 0.3
PING_MAX_INTERVAL = 3.0
SERVER_IGNORE_PROBABILITY = 0.1
SERVER_RESPONSE_MIN_DELAY = 0.1
SERVER_RESPONSE_MAX_DELAY = 1.0
KEEPALIVE_INTERVAL = 5.0
RUN_DURATION = 300.0

LOG_DIR = "logs"
SERVER_LOG_FILE = "server.log"
CLIENT_LOG_TEMPLATE = "client_{}.log"